# Generated by Django 4.1.3 on 2022-12-05 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('CI', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=30)),
                ('municipio_residencia', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('lote1', models.IntegerField()),
                ('lote2', models.IntegerField()),
                ('lote3', models.IntegerField()),
                ('fecha1', models.DateField()),
                ('fecha2', models.DateField()),
                ('fecha3', models.DateField()),
                ('hora1', models.TimeField()),
                ('hora2', models.TimeField()),
                ('hora3', models.TimeField()),
                ('enfermera1', models.CharField(max_length=50)),
                ('enfermera2', models.CharField(max_length=50)),
                ('enfermera3', models.CharField(max_length=50)),
                ('HC', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.hc')),
            ],
        ),
    ]
