# Generated by Django 4.1.3 on 2022-12-05 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_hc_ci_alter_hc_telefono_alter_tv_lote1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tv',
            old_name='enfermera1',
            new_name='enfermera_primera_dosis',
        ),
        migrations.RenameField(
            model_name='tv',
            old_name='enfermera2',
            new_name='enfermera_segunda_dosis',
        ),
        migrations.RenameField(
            model_name='tv',
            old_name='enfermera3',
            new_name='enfermera_tercera_dosis',
        ),
        migrations.RenameField(
            model_name='tv',
            old_name='fecha1',
            new_name='fecha_primera_dosis',
        ),
        migrations.RenameField(
            model_name='tv',
            old_name='fecha2',
            new_name='fecha_segunda_dosis',
        ),
        migrations.RenameField(
            model_name='tv',
            old_name='fecha3',
            new_name='fecha_tercera_dosis',
        ),
        migrations.RenameField(
            model_name='tv',
            old_name='hora1',
            new_name='hora_primera_dosis',
        ),
        migrations.RenameField(
            model_name='tv',
            old_name='hora2',
            new_name='hora_segunda_dosis',
        ),
        migrations.RenameField(
            model_name='tv',
            old_name='hora3',
            new_name='hora_tercera_dosis',
        ),
        migrations.RenameField(
            model_name='tv',
            old_name='lote1',
            new_name='lote_primera_dosis',
        ),
        migrations.RenameField(
            model_name='tv',
            old_name='lote2',
            new_name='lote_segunda_dosis',
        ),
        migrations.RenameField(
            model_name='tv',
            old_name='lote3',
            new_name='lote_tercera_dosis',
        ),
    ]
