# Generated by Django 4.1.3 on 2022-12-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_enfermera1_tv_enfermera_primera_dosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv',
            name='fecha_primera_dosis',
            field=models.Field(blank=True),
        ),
        migrations.AlterField(
            model_name='tv',
            name='lote_primera_dosis',
            field=models.Field(blank=True),
        ),
    ]
