# Generated by Django 4.1.3 on 2022-12-06 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_hc_historiaclinica'),
    ]

    operations = [
        migrations.CreateModel(
            name='HC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('CI', models.CharField(max_length=11)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='tv',
            name='HC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.hc'),
        ),
        migrations.DeleteModel(
            name='HistoriaClinica',
        ),
    ]
