# Generated by Django 4.1.3 on 2022-12-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_descripcion_hc_descripción_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hc',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='hc',
            old_name='dirección',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='hc',
            old_name='teléfono',
            new_name='telefono',
        ),
        migrations.AlterField(
            model_name='hc',
            name='sexo',
            field=models.IntegerField(choices=[[0, 'Masculino'], [1, 'Femenino']]),
        ),
    ]
